name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: ${{ github.repository_owner == 'none' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install libusb-1.0-0-dev
          sudo apt-get install libudev-dev

      - name: Install dependencies
        run: |
          yarn

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn lint
          yarn build
          yarn package
          yarn test
          yarn postinstall
          yarn build
          yarn electron-builder -- --publish onTag --win --mac --linux
