name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install libs
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install libusb-1.0-0-dev
          sudo apt-get install libudev-dev

      - name: Install
        run: |
          yarn

      - name: Build
        run: |
          yarn build

      - name: Test
        run: |
          yarn lint
          yarn test

      - name: Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package
